/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Principal.GestoraEmpresa;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.Image;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import Principal.Mensajes;
import javafx.scene.control.CheckBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author NEWASUSOJO2
 */
public class VentanaAltas extends javax.swing.JFrame {

    VentanaAcceso ventanaAcceso = new VentanaAcceso();

    /**
     * Creates new form VentanaAltas
     */
    public VentanaAltas() {
        initComponents();
        try {
            Image icono = new ImageIcon("src/Imagenes/favicon.png").getImage();
            setIconImage(icono);
        } catch (NullPointerException errorIcono) {

        }
    }
    GestoraEmpresa laGestora = new GestoraEmpresa();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_principal = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        b_menu = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        p_trabajador = new javax.swing.JPanel();
        e_dni = new javax.swing.JLabel();
        e_nombre = new javax.swing.JLabel();
        e_apellidos = new javax.swing.JLabel();
        e_anioIngreso = new javax.swing.JLabel();
        e_seccion = new javax.swing.JLabel();
        ct_dni = new javax.swing.JTextField();
        ct_nombreTrabajador = new javax.swing.JTextField();
        ct_apellidosTrabajador = new javax.swing.JTextField();
        ct_anioIngreso = new javax.swing.JTextField();
        cb_seccion = new javax.swing.JComboBox<>();
        b_limpiarTrabajador = new javax.swing.JButton();
        b_guardarTrabajador = new javax.swing.JButton();
        p_autobus = new javax.swing.JPanel();
        e_matricula = new javax.swing.JLabel();
        e_fabricante = new javax.swing.JLabel();
        e_modelo = new javax.swing.JLabel();
        e_motor = new javax.swing.JLabel();
        e_plazas = new javax.swing.JLabel();
        e_precio = new javax.swing.JLabel();
        e_combustible = new javax.swing.JLabel();
        b_limpiarAutobus = new javax.swing.JButton();
        b_guardarAutobus = new javax.swing.JButton();
        ct_matricula = new javax.swing.JTextField();
        ct_fabricante = new javax.swing.JTextField();
        ct_modelo = new javax.swing.JTextField();
        ct_motor = new javax.swing.JTextField();
        cb_combustible = new javax.swing.JComboBox<>();
        ct_plazas = new javax.swing.JTextField();
        ct_precio = new javax.swing.JTextField();
        p_cliente = new javax.swing.JPanel();
        e_nombreCliente = new javax.swing.JLabel();
        ct_nombreCliente = new javax.swing.JTextField();
        e_localidadCliente = new javax.swing.JLabel();
        ct_localidadCliente = new javax.swing.JTextField();
        e_telefonoCliente = new javax.swing.JLabel();
        ct_telefonoCliente = new javax.swing.JTextField();
        b_limpiarCliente = new javax.swing.JButton();
        b_guardarCliente = new javax.swing.JButton();
        p_ruta = new javax.swing.JPanel();
        e_ciudadInicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ct_inicioRuta = new javax.swing.JTextField();
        ct_finRuta = new javax.swing.JTextField();
        ct_kilometros = new javax.swing.JTextField();
        cb_conductorRuta = new javax.swing.JComboBox<>();
        cb_autobusRuta = new javax.swing.JComboBox<>();
        b_limpiarRuta = new javax.swing.JButton();
        b_guardarRuta = new javax.swing.JButton();
        b_ventanaInforRuta = new javax.swing.JButton();
        p_factura = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cb_clienteFactura = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_rutaFactura = new javax.swing.JComboBox<>();
        b_limpiarFactura = new javax.swing.JButton();
        b_guardarFactura = new javax.swing.JButton();
        b_ventanaInforfactura = new javax.swing.JButton();
        p_usuario = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cb_trabajadores = new javax.swing.JComboBox<>();
        ct_clave1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        ct_clave2 = new javax.swing.JPasswordField();
        b_limpiarUsuario = new javax.swing.JButton();
        b_ventanaInforUsuario = new javax.swing.JButton();
        b_guardarUsuario = new javax.swing.JButton();
        b_privilegios = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Altas – GESTIÓN DE EMPRESA ©");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("SELECCIONE UNA PESTAÑA PARA GENERAR LA NUEVA INFORMACIÓN");

        b_menu.setText("<-- VOLVER A MENÚ");
        b_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menuActionPerformed(evt);
            }
        });

        b_salir.setText("SALIR DEL PROGRAMA");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        e_dni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_dni.setText("DNI:");

        e_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_nombre.setText("NOMBRE:");

        e_apellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_apellidos.setText("APELLIDOS:");

        e_anioIngreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_anioIngreso.setText("AÑO DE INGRESO:");

        e_seccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_seccion.setText("SECCIÓN:");

        ct_dni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_nombreTrabajador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_apellidosTrabajador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_anioIngreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cb_seccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_seccion.setModel(new DefaultComboBoxModel(laGestora.getLasSecciones()));

        b_limpiarTrabajador.setText("LIMPIAR");
        b_limpiarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarTrabajadorActionPerformed(evt);
            }
        });

        b_guardarTrabajador.setText("GUARDAR");
        b_guardarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_trabajadorLayout = new javax.swing.GroupLayout(p_trabajador);
        p_trabajador.setLayout(p_trabajadorLayout);
        p_trabajadorLayout.setHorizontalGroup(
            p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_trabajadorLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(e_seccion)
                    .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(e_anioIngreso)
                        .addComponent(e_apellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(e_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(e_dni, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(42, 42, 42)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ct_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_apellidosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_nombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cb_seccion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ct_anioIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(p_trabajadorLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(b_limpiarTrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_guardarTrabajador)
                .addGap(67, 67, 67))
        );
        p_trabajadorLayout.setVerticalGroup(
            p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_trabajadorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_dni)
                    .addComponent(ct_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_nombre)
                    .addComponent(ct_nombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_apellidos)
                    .addComponent(ct_apellidosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_anioIngreso)
                    .addComponent(ct_anioIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_seccion)
                    .addComponent(cb_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_limpiarTrabajador)
                    .addComponent(b_guardarTrabajador))
                .addGap(47, 47, 47))
        );

        jTabbedPane7.addTab("-- TRABAJADOR --", p_trabajador);

        e_matricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_matricula.setText("MATRICULA:");

        e_fabricante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_fabricante.setText("FABRICANTE:");

        e_modelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_modelo.setText("MODELO:");

        e_motor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_motor.setText("FABRICANTE MOTOR:");

        e_plazas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_plazas.setText("PLAZAS:");

        e_precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_precio.setText("PRECIO:");

        e_combustible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_combustible.setText("TIPO DE COMBUSTIBLE:");

        b_limpiarAutobus.setText("LIMPIAR");
        b_limpiarAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarAutobusActionPerformed(evt);
            }
        });

        b_guardarAutobus.setText("GUARDAR");
        b_guardarAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarAutobusActionPerformed(evt);
            }
        });

        ct_matricula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_fabricante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_modelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_motor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cb_combustible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_combustible.setModel(new DefaultComboBoxModel(laGestora.getLosCombustibles()));

        ct_plazas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout p_autobusLayout = new javax.swing.GroupLayout(p_autobus);
        p_autobus.setLayout(p_autobusLayout);
        p_autobusLayout.setHorizontalGroup(
            p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_autobusLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(b_limpiarAutobus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_guardarAutobus)
                .addGap(56, 56, 56))
            .addGroup(p_autobusLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(e_precio)
                    .addComponent(e_fabricante)
                    .addComponent(e_matricula)
                    .addComponent(e_modelo)
                    .addComponent(e_motor)
                    .addComponent(e_combustible)
                    .addComponent(e_plazas))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ct_matricula)
                    .addComponent(ct_fabricante)
                    .addComponent(ct_modelo)
                    .addComponent(ct_motor)
                    .addComponent(ct_plazas)
                    .addComponent(ct_precio)
                    .addComponent(cb_combustible, 0, 150, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        p_autobusLayout.setVerticalGroup(
            p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_autobusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_matricula)
                    .addComponent(ct_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_fabricante)
                    .addComponent(ct_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_modelo)
                    .addComponent(ct_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_motor)
                    .addComponent(ct_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_combustible)
                    .addComponent(cb_combustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_plazas)
                    .addComponent(ct_plazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_precio)
                    .addComponent(ct_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_limpiarAutobus)
                    .addComponent(b_guardarAutobus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("-- AUTOBÚS --", p_autobus);

        e_nombreCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_nombreCliente.setText("NOMBRE:");

        ct_nombreCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        e_localidadCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_localidadCliente.setText("LOCALIDAD:");

        ct_localidadCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        e_telefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_telefonoCliente.setText("TELÉFONO:");

        ct_telefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        b_limpiarCliente.setText("LIMPIAR");
        b_limpiarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarClienteActionPerformed(evt);
            }
        });

        b_guardarCliente.setText("GUARDAR");
        b_guardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_clienteLayout = new javax.swing.GroupLayout(p_cliente);
        p_cliente.setLayout(p_clienteLayout);
        p_clienteLayout.setHorizontalGroup(
            p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_clienteLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p_clienteLayout.createSequentialGroup()
                        .addComponent(e_nombreCliente)
                        .addGap(18, 18, 18)
                        .addComponent(ct_nombreCliente))
                    .addGroup(p_clienteLayout.createSequentialGroup()
                        .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_localidadCliente)
                            .addComponent(e_telefonoCliente))
                        .addGap(18, 18, 18)
                        .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ct_localidadCliente)
                            .addGroup(p_clienteLayout.createSequentialGroup()
                                .addComponent(ct_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 212, Short.MAX_VALUE)))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(p_clienteLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(b_limpiarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_guardarCliente)
                .addGap(50, 50, 50))
        );
        p_clienteLayout.setVerticalGroup(
            p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_clienteLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_nombreCliente)
                    .addComponent(ct_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_localidadCliente)
                    .addComponent(ct_localidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_telefonoCliente)
                    .addComponent(ct_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_limpiarCliente)
                    .addComponent(b_guardarCliente))
                .addGap(46, 46, 46))
        );

        jTabbedPane7.addTab("-- CLIENTE --", p_cliente);

        e_ciudadInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        e_ciudadInicio.setText("CIUDAD DE INICIO:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CIUDAD DE DESTINO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("DISTANCIA ENTRE INICIO Y FIN (en km):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CONDUCTOR:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("AUTOBÚS:");

        ct_inicioRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_finRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ct_kilometros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cb_conductorRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_conductorRuta.setModel(new DefaultComboBoxModel(laGestora.getLosDNIdeConductores()));

        cb_autobusRuta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_autobusRuta.setModel(new DefaultComboBoxModel(laGestora.getLasMatriculas()));

        b_limpiarRuta.setText("LIMPIAR");

        b_guardarRuta.setText("GUARDAR");
        b_guardarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarRutaActionPerformed(evt);
            }
        });

        b_ventanaInforRuta.setText("ABRIR VENTANA INFORMACIÓN");
        b_ventanaInforRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ventanaInforRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_rutaLayout = new javax.swing.GroupLayout(p_ruta);
        p_ruta.setLayout(p_rutaLayout);
        p_rutaLayout.setHorizontalGroup(
            p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_rutaLayout.createSequentialGroup()
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_rutaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(e_ciudadInicio)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ct_inicioRuta)
                            .addComponent(ct_finRuta)
                            .addComponent(ct_kilometros)
                            .addComponent(cb_conductorRuta, 0, 150, Short.MAX_VALUE)
                            .addComponent(cb_autobusRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(p_rutaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_limpiarRuta)
                        .addGap(109, 109, 109)
                        .addComponent(b_ventanaInforRuta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(b_guardarRuta)
                .addContainerGap())
        );
        p_rutaLayout.setVerticalGroup(
            p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_rutaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_ciudadInicio)
                    .addComponent(ct_inicioRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ct_finRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ct_kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_conductorRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_autobusRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ventanaInforRuta)
                    .addComponent(b_guardarRuta)
                    .addComponent(b_limpiarRuta))
                .addGap(43, 43, 43))
        );

        jLabel2.getAccessibleContext().setAccessibleDescription("Los kilómetros sin decimales.");

        jTabbedPane7.addTab("-- RUTA --", p_ruta);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CLIENTE:");

        cb_clienteFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_clienteFactura.setModel(new DefaultComboBoxModel(laGestora.getLosCodClientes()));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("RUTA SOLICITADA:");

        cb_rutaFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_rutaFactura.setModel(new DefaultComboBoxModel(laGestora.getLosCodRutas()));

        b_limpiarFactura.setText("LIMPIAR");
        b_limpiarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarFacturaActionPerformed(evt);
            }
        });

        b_guardarFactura.setText("GUARDAR");
        b_guardarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarFacturaActionPerformed(evt);
            }
        });

        b_ventanaInforfactura.setText("ABRIR VENTANA INFORMACIÓN");
        b_ventanaInforfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ventanaInforfacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_facturaLayout = new javax.swing.GroupLayout(p_factura);
        p_factura.setLayout(p_facturaLayout);
        p_facturaLayout.setHorizontalGroup(
            p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_facturaLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_clienteFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_rutaFactura, 0, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_facturaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(b_limpiarFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(b_ventanaInforfactura)
                .addGap(89, 89, 89)
                .addComponent(b_guardarFactura)
                .addGap(28, 28, 28))
        );
        p_facturaLayout.setVerticalGroup(
            p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_facturaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_clienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_rutaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_limpiarFactura)
                    .addComponent(b_guardarFactura)
                    .addComponent(b_ventanaInforfactura))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("-- FACTURA --", p_factura);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NIF DEL USUARIO:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CLAVE DEL USUARIO:");

        cb_trabajadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_trabajadores.setModel(new DefaultComboBoxModel(laGestora.getLosDNIdeDireccion()));

        ct_clave1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("CONFIRMAR CLAVE:");

        ct_clave2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        b_limpiarUsuario.setText("LIMPIAR");
        b_limpiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarUsuarioActionPerformed(evt);
            }
        });

        b_ventanaInforUsuario.setText("ABRIR VENTANA DE INFORMACIÓN");
        b_ventanaInforUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ventanaInforUsuarioActionPerformed(evt);
            }
        });

        b_guardarUsuario.setText("GUARDAR");
        b_guardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarUsuarioActionPerformed(evt);
            }
        });

        b_privilegios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        b_privilegios.setText("PRIVILEGIOS DE ADMINISTRADOR");

        javax.swing.GroupLayout p_usuarioLayout = new javax.swing.GroupLayout(p_usuario);
        p_usuario.setLayout(p_usuarioLayout);
        p_usuarioLayout.setHorizontalGroup(
            p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_usuarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(b_limpiarUsuario)
                .addGap(81, 81, 81)
                .addComponent(b_ventanaInforUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(b_guardarUsuario)
                .addGap(42, 42, 42))
            .addGroup(p_usuarioLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_privilegios)
                    .addGroup(p_usuarioLayout.createSequentialGroup()
                        .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(73, 73, 73)
                        .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ct_clave1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_trabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ct_clave2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_usuarioLayout.setVerticalGroup(
            p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_usuarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_trabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ct_clave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(ct_clave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(b_privilegios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(p_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_limpiarUsuario)
                    .addComponent(b_ventanaInforUsuario)
                    .addComponent(b_guardarUsuario))
                .addGap(57, 57, 57))
        );

        jTabbedPane7.addTab("-- USUARIO --", p_usuario);

        javax.swing.GroupLayout p_principalLayout = new javax.swing.GroupLayout(p_principal);
        p_principal.setLayout(p_principalLayout);
        p_principalLayout.setHorizontalGroup(
            p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
            .addGroup(p_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextArea1)
                    .addGroup(p_principalLayout.createSequentialGroup()
                        .addComponent(b_menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_salir)))
                .addContainerGap())
        );
        p_principalLayout.setVerticalGroup(
            p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_menu)
                    .addComponent(b_salir))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        this.setVisible(false);
        Mensajes.mensajeDeSalida();
        System.exit(0);
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menuActionPerformed
        VentanaMenu elMenu = new VentanaMenu();
        this.setVisible(false);
        elMenu.setVisible(true);
    }//GEN-LAST:event_b_menuActionPerformed

    private void b_limpiarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarTrabajadorActionPerformed
        limpiar(p_trabajador);
    }//GEN-LAST:event_b_limpiarTrabajadorActionPerformed

    private void b_guardarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarTrabajadorActionPerformed
        guardarTrabajador();
    }//GEN-LAST:event_b_guardarTrabajadorActionPerformed

    private void b_ventanaInforRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ventanaInforRutaActionPerformed
        abrirVentanaInformacion();
    }//GEN-LAST:event_b_ventanaInforRutaActionPerformed

    private void b_ventanaInforfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ventanaInforfacturaActionPerformed
        abrirVentanaInformacion();
    }//GEN-LAST:event_b_ventanaInforfacturaActionPerformed

    private void b_limpiarAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarAutobusActionPerformed
        limpiar(p_autobus);
    }//GEN-LAST:event_b_limpiarAutobusActionPerformed

    private void b_guardarAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarAutobusActionPerformed
        guardarAutobus();
    }//GEN-LAST:event_b_guardarAutobusActionPerformed

    private void b_limpiarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarClienteActionPerformed
        limpiar(p_cliente);
    }//GEN-LAST:event_b_limpiarClienteActionPerformed

    private void b_guardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarClienteActionPerformed
        guardarCliente();
    }//GEN-LAST:event_b_guardarClienteActionPerformed

    private void b_guardarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarRutaActionPerformed
        guardarRuta();
    }//GEN-LAST:event_b_guardarRutaActionPerformed

    private void b_limpiarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarFacturaActionPerformed
        limpiar(p_factura);
    }//GEN-LAST:event_b_limpiarFacturaActionPerformed

    private void b_guardarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarFacturaActionPerformed
        guardarFactura();
    }//GEN-LAST:event_b_guardarFacturaActionPerformed

    private void b_ventanaInforUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ventanaInforUsuarioActionPerformed
        abrirVentanaInformacion();
    }//GEN-LAST:event_b_ventanaInforUsuarioActionPerformed

    private void b_limpiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarUsuarioActionPerformed
        limpiar(p_usuario);
        b_privilegios.setSelected(false);
    }//GEN-LAST:event_b_limpiarUsuarioActionPerformed

    private void b_guardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarUsuarioActionPerformed
        guardarUsuario();
    }//GEN-LAST:event_b_guardarUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void guardarTrabajador() throws HeadlessException {
        try {
            String dni = (ct_dni.getText()).toUpperCase();
            String nombre = (ct_nombreTrabajador.getText()).toUpperCase();
            String apellido = (ct_apellidosTrabajador.getText()).toUpperCase();
            String nomApe = apellido + ", " + nombre;
            int anio = Integer.parseInt(ct_anioIngreso.getText());
            String seccion = cb_seccion.getItemAt(cb_seccion.getSelectedIndex());
            if (Pattern.matches("[0-9]{8}[A-Z]{1}", dni)) {
                if ((laGestora.nuevoTrabajador(dni, nomApe, anio, seccion)) == true) {
                    limpiar(p_trabajador);
                    escribirArchivos();
                }
            } else {
                Mensajes.mensajesDeError("DNI");
            }

        } catch (NumberFormatException exNumero) {
            Mensajes.mensajesDeError("ANIO");
        }
    }

    private void guardarAutobus() throws HeadlessException {
        try {
            String matricula = (ct_matricula.getText()).toUpperCase();
            String fabricante = (ct_fabricante.getText()).toUpperCase();
            String modelo = (ct_modelo.getText()).toUpperCase();
            String motor = (ct_motor.getText()).toUpperCase();
            String combustible = cb_combustible.getItemAt(cb_combustible.getSelectedIndex()).toUpperCase();
            int plazas = Integer.parseInt(ct_plazas.getText());
            int precio = Integer.parseInt(ct_precio.getText());
            if (laGestora.comprobarMatricula(matricula)) {
                if (plazas >= 10 && plazas <= 70) {
                    if (precio >= 20000) {
                        if (laGestora.nuevoAutobus(matricula, fabricante, modelo, motor, combustible, plazas, precio) == true) {
                            limpiar(p_autobus);
                            escribirArchivos();
                        }
                    } else {
                        Mensajes.mensajesDeError("PRECIO");
                    }
                } else {
                    Mensajes.mensajesDeError("PLAZAS");
                }
            } else {
                Mensajes.mensajesDeError("MATRICULA");
            }

        } catch (NumberFormatException exNumero) {
            Mensajes.mensajesDeError("GENERAL");
        }
    }

    private void guardarRuta() {
        String inicio = (ct_inicioRuta.getText()).toUpperCase();
        String destino = (ct_finRuta.getText()).toUpperCase();
        String kilometros = (ct_kilometros.getText());
        String conductor = cb_conductorRuta.getItemAt(cb_conductorRuta.getSelectedIndex());
        String autobus = cb_autobusRuta.getItemAt(cb_autobusRuta.getSelectedIndex());
        if (Pattern.matches("[0-9]+", kilometros) == true) {
            String cod = null;
            try {
                cod = generarCodigoRuta(inicio, destino, kilometros);
            } catch (Exception ex1) {
                Mensajes.mensajesDeError("GENERAL");
            }
            int distancia = Integer.parseInt(kilometros);
            if (cod != null) {
                laGestora.nuevaRuta(cod, inicio, destino, distancia, conductor, autobus);
                limpiar(p_ruta);
                escribirArchivos();
            }
        } else {
            Mensajes.mensajesDeError("KILOMETROS");
        }
    }

    private void guardarCliente() throws NumberFormatException, HeadlessException {
        String nombre = (ct_nombreCliente.getText()).toUpperCase();
        String localidad = (ct_localidadCliente.getText()).toUpperCase();
        String tele = (ct_telefonoCliente.getText());
        if (tele.length() == 9) {
            int telefono = Integer.parseInt(tele);
            String letras = nombre.substring(0, 3);
            int numero = (int) (Math.random() * 1000);
            String codCliente = letras + numero;
            if (laGestora.nuevoCliente(codCliente, nombre, localidad, telefono) == true) {
                limpiar(p_cliente);
                escribirArchivos();
            } else {
                guardarCliente();
            }
        } else {
            Mensajes.mensajesDeError("TELEFONO");
        }
    }

    private void guardarFactura() {
        String cliente = cb_clienteFactura.getItemAt(cb_clienteFactura.getSelectedIndex());
        String ruta = cb_rutaFactura.getItemAt(cb_rutaFactura.getSelectedIndex());
        if (laGestora.nuevaFactura(cliente, ruta) == true) {
            limpiar(p_factura);
            escribirArchivos();
        } else {
            Mensajes.mensajesDeError("FACTURA");
        }

    }

    private void guardarUsuario() {
        String usuario = cb_trabajadores.getItemAt(cb_trabajadores.getSelectedIndex());
        String clave1 = new String(ct_clave1.getPassword());
        String clave2 = new String(ct_clave2.getPassword());
        boolean privilegios = b_privilegios.isSelected();
        if (clave1.equals(clave2)) {
            if (laGestora.nuevoUsuario(usuario, clave1, privilegios) == true) {
                limpiar(p_usuario);
                escribirArchivos();
            }
        } else {
            Mensajes.mensajesDeError("CLAVES_DISTINTAS");
        }
    }

    private String generarCodigoRuta(String inicio, String fin, String kilometros) {
        while (kilometros.length() < 5) {
            kilometros = 0 + kilometros;
        }
        String letraInicio = inicio.substring(0, 1);
        String letraFin = fin.substring(0, 1);
        String codigoRuta = letraInicio + letraFin + kilometros;
        System.out.println(codigoRuta);
        return codigoRuta;
    }

    private void abrirVentanaInformacion() {
        VentanaBajas lasBajas = new VentanaBajas();
        lasBajas.setVisible(true);
        lasBajas.mostrarBotonCerrarVentana(true);
    }

    private void escribirArchivos() {
        laGestora.escribirArchivos();
    }

    private void limpiar(JPanel elPanel) {
        Component[] losComponentes = elPanel.getComponents();
        for (Component elComponente : losComponentes) {
            if (elComponente instanceof JTextField) {
                JTextField ct = (JTextField) elComponente;
                ct.setText(null);
            }
            if (elComponente instanceof JComboBox) {
                JComboBox cb = (JComboBox) elComponente;
                cb.setSelectedIndex(0);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardarAutobus;
    private javax.swing.JButton b_guardarCliente;
    private javax.swing.JButton b_guardarFactura;
    private javax.swing.JButton b_guardarRuta;
    private javax.swing.JButton b_guardarTrabajador;
    private javax.swing.JButton b_guardarUsuario;
    private javax.swing.JButton b_limpiarAutobus;
    private javax.swing.JButton b_limpiarCliente;
    private javax.swing.JButton b_limpiarFactura;
    private javax.swing.JButton b_limpiarRuta;
    private javax.swing.JButton b_limpiarTrabajador;
    private javax.swing.JButton b_limpiarUsuario;
    private javax.swing.JButton b_menu;
    private javax.swing.JCheckBox b_privilegios;
    private javax.swing.JButton b_salir;
    private javax.swing.JButton b_ventanaInforRuta;
    private javax.swing.JButton b_ventanaInforUsuario;
    private javax.swing.JButton b_ventanaInforfactura;
    private javax.swing.JComboBox<String> cb_autobusRuta;
    private javax.swing.JComboBox<String> cb_clienteFactura;
    private javax.swing.JComboBox<String> cb_combustible;
    private javax.swing.JComboBox<String> cb_conductorRuta;
    private javax.swing.JComboBox<String> cb_rutaFactura;
    private javax.swing.JComboBox<String> cb_seccion;
    private javax.swing.JComboBox<String> cb_trabajadores;
    private javax.swing.JTextField ct_anioIngreso;
    private javax.swing.JTextField ct_apellidosTrabajador;
    private javax.swing.JPasswordField ct_clave1;
    private javax.swing.JPasswordField ct_clave2;
    private javax.swing.JTextField ct_dni;
    private javax.swing.JTextField ct_fabricante;
    private javax.swing.JTextField ct_finRuta;
    private javax.swing.JTextField ct_inicioRuta;
    private javax.swing.JTextField ct_kilometros;
    private javax.swing.JTextField ct_localidadCliente;
    private javax.swing.JTextField ct_matricula;
    private javax.swing.JTextField ct_modelo;
    private javax.swing.JTextField ct_motor;
    private javax.swing.JTextField ct_nombreCliente;
    private javax.swing.JTextField ct_nombreTrabajador;
    private javax.swing.JTextField ct_plazas;
    private javax.swing.JTextField ct_precio;
    private javax.swing.JTextField ct_telefonoCliente;
    private javax.swing.JLabel e_anioIngreso;
    private javax.swing.JLabel e_apellidos;
    private javax.swing.JLabel e_ciudadInicio;
    private javax.swing.JLabel e_combustible;
    private javax.swing.JLabel e_dni;
    private javax.swing.JLabel e_fabricante;
    private javax.swing.JLabel e_localidadCliente;
    private javax.swing.JLabel e_matricula;
    private javax.swing.JLabel e_modelo;
    private javax.swing.JLabel e_motor;
    private javax.swing.JLabel e_nombre;
    private javax.swing.JLabel e_nombreCliente;
    private javax.swing.JLabel e_plazas;
    private javax.swing.JLabel e_precio;
    private javax.swing.JLabel e_seccion;
    private javax.swing.JLabel e_telefonoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel p_autobus;
    private javax.swing.JPanel p_cliente;
    private javax.swing.JPanel p_factura;
    private javax.swing.JPanel p_principal;
    private javax.swing.JPanel p_ruta;
    private javax.swing.JPanel p_trabajador;
    private javax.swing.JPanel p_usuario;
    // End of variables declaration//GEN-END:variables
}
