/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ModeloTablas.ModeloTrabajador;
import ModeloTablas.ModeloCliente;
import ModeloTablas.ModeloRuta;
import ModeloTablas.ModeloFactura;
import ModeloTablas.ModeloUsuario;
import Principal.GestoraEmpresa;
import Principal.ModeloAutobuses;
import Principal.Mensajes;
import java.awt.Component;

import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author NEWASUSOJO2
 */
public class VentanaBajas extends javax.swing.JFrame {

    VentanaAcceso ventanaAcceso = new VentanaAcceso();
    GestoraEmpresa laGestora = new GestoraEmpresa();
    boolean filtrar = false;

    ModeloTrabajador moTrab = new ModeloTrabajador(laGestora.getLosTrabajadores());

    String fabricante = "TODOS";
    ModeloAutobuses moAuto = new ModeloAutobuses(laGestora.getLosAutobuses(fabricante));

    /**
     * Creates new form VentanaBajas
     */
    public VentanaBajas() {
        initComponents();

        try {
            Image icono = new ImageIcon("src/Imagenes/favicon.png").getImage();
            setIconImage(icono);
        } catch (NullPointerException errorIcono) {

        }
        mostrarBotonCerrarVentana(false);
    }

    /**
     * Cuando se abre la ventana desde la ventana Altas, se muestra un botón que
     * permite cerrar esta ventana y no el programa entero.
     *
     * @param caso
     */
    public void mostrarBotonCerrarVentana(boolean caso) {
        b_cerrarVentana.setVisible(caso);
        b_menu.setEnabled(!caso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_principal = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        p_trabajador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_trabajador = new javax.swing.JTable();
        b_bajaTrabajador = new javax.swing.JButton();
        p_autobus = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_autobus = new javax.swing.JTable();
        b_bajaAutobus = new javax.swing.JButton();
        cb_fabricanteCarroceria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        p_cliente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_cliente = new javax.swing.JTable();
        p_ruta = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        t_ruta = new javax.swing.JTable();
        p_factura = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        t_factura = new javax.swing.JTable();
        p_usuarios = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_usuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ct_clave = new javax.swing.JTextField();
        p_cambiarClaveUsuario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ct_clave1 = new javax.swing.JPasswordField();
        ct_clave2 = new javax.swing.JPasswordField();
        b_guardarNuevaClave = new javax.swing.JButton();
        b_limpiarUsuario = new javax.swing.JButton();
        b_cambiarClave = new javax.swing.JToggleButton();
        b_eliminarUsuario = new javax.swing.JButton();
        b_menu = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        b_cerrarVentana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información – GESTIÓN DE EMPRESA ©");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        p_principal.setPreferredSize(new java.awt.Dimension(540, 399));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("SELECCIONE UNA PESTAÑA PARA MOSTRAR LA INFORMACIÓN");

        t_trabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_trabajador);

        b_bajaTrabajador.setText("DAR DE BAJA TRABAJADORES SELECCIONADOS");
        b_bajaTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bajaTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_trabajadorLayout = new javax.swing.GroupLayout(p_trabajador);
        p_trabajador.setLayout(p_trabajadorLayout);
        p_trabajadorLayout.setHorizontalGroup(
            p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addGroup(p_trabajadorLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(b_bajaTrabajador)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_trabajadorLayout.setVerticalGroup(
            p_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_trabajadorLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(b_bajaTrabajador)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("-- TRABAJADOR --", p_trabajador);

        t_autobus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_autobus);

        b_bajaAutobus.setText("DAR DE BAJA AUTOBUSES SELECCIONADOS");
        b_bajaAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bajaAutobusActionPerformed(evt);
            }
        });

        cb_fabricanteCarroceria.setModel(new DefaultComboBoxModel(laGestora.getLosFabricantes()));
        cb_fabricanteCarroceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fabricanteCarroceriaActionPerformed(evt);
            }
        });

        jLabel1.setText("FABRICANTE (CARROCERÍA): ");

        javax.swing.GroupLayout p_autobusLayout = new javax.swing.GroupLayout(p_autobus);
        p_autobus.setLayout(p_autobusLayout);
        p_autobusLayout.setHorizontalGroup(
            p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addGroup(p_autobusLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cb_fabricanteCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_autobusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_bajaAutobus)
                .addGap(173, 173, 173))
        );
        p_autobusLayout.setVerticalGroup(
            p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_autobusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_autobusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fabricanteCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(b_bajaAutobus)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("-- AUTOBÚS --", p_autobus);

        t_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(t_cliente);

        javax.swing.GroupLayout p_clienteLayout = new javax.swing.GroupLayout(p_cliente);
        p_cliente.setLayout(p_clienteLayout);
        p_clienteLayout.setHorizontalGroup(
            p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        p_clienteLayout.setVerticalGroup(
            p_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("-- CLIENTE --", p_cliente);

        t_ruta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(t_ruta);

        javax.swing.GroupLayout p_rutaLayout = new javax.swing.GroupLayout(p_ruta);
        p_ruta.setLayout(p_rutaLayout);
        p_rutaLayout.setHorizontalGroup(
            p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        p_rutaLayout.setVerticalGroup(
            p_rutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("-- RUTA --", p_ruta);

        t_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(t_factura);

        javax.swing.GroupLayout p_facturaLayout = new javax.swing.GroupLayout(p_factura);
        p_factura.setLayout(p_facturaLayout);
        p_facturaLayout.setHorizontalGroup(
            p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        p_facturaLayout.setVerticalGroup(
            p_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("-- FACTURA --", p_factura);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("USUARIO:");

        cb_usuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cb_usuario.setModel(new DefaultComboBoxModel(laGestora.getLosDNIdeDireccion()));
        cb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("CLAVE:");

        ct_clave.setEditable(false);
        ct_clave.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("NUEVA CLAVE:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("REPETIR CLAVE:");

        ct_clave1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        ct_clave2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        b_guardarNuevaClave.setText("GUARDAR");
        b_guardarNuevaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarNuevaClaveActionPerformed(evt);
            }
        });

        b_limpiarUsuario.setText("LIMPIAR");
        b_limpiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_cambiarClaveUsuarioLayout = new javax.swing.GroupLayout(p_cambiarClaveUsuario);
        p_cambiarClaveUsuario.setLayout(p_cambiarClaveUsuarioLayout);
        p_cambiarClaveUsuarioLayout.setHorizontalGroup(
            p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cambiarClaveUsuarioLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(81, 81, 81)
                .addGroup(p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ct_clave1)
                    .addComponent(ct_clave2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_cambiarClaveUsuarioLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(b_limpiarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_guardarNuevaClave)
                .addGap(110, 110, 110))
        );
        p_cambiarClaveUsuarioLayout.setVerticalGroup(
            p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cambiarClaveUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ct_clave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ct_clave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_cambiarClaveUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_guardarNuevaClave)
                    .addComponent(b_limpiarUsuario))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        b_cambiarClave.setText("CAMBIAR CLAVE");
        b_cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cambiarClaveActionPerformed(evt);
            }
        });

        b_eliminarUsuario.setText("ELIMINAR USUARIO");
        b_eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_usuariosLayout = new javax.swing.GroupLayout(p_usuarios);
        p_usuarios.setLayout(p_usuariosLayout);
        p_usuariosLayout.setHorizontalGroup(
            p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_cambiarClaveUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(p_usuariosLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(p_usuariosLayout.createSequentialGroup()
                        .addComponent(b_cambiarClave)
                        .addGap(21, 21, 21)))
                .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_usuariosLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_usuario, 0, 125, Short.MAX_VALUE)
                            .addComponent(ct_clave)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_usuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        p_usuariosLayout.setVerticalGroup(
            p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_usuariosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ct_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(p_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cambiarClave)
                    .addComponent(b_eliminarUsuario))
                .addGap(18, 18, 18)
                .addComponent(p_cambiarClaveUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("-- USUARIO --", p_usuarios);

        b_menu.setText("<-- VOLVER A MENÚ");
        b_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menuActionPerformed(evt);
            }
        });

        b_salir.setText("SALIR DEL PROGRAMA");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        b_cerrarVentana.setText("CERRAR LA VENTANA");
        b_cerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerrarVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_principalLayout = new javax.swing.GroupLayout(p_principal);
        p_principal.setLayout(p_principalLayout);
        p_principalLayout.setHorizontalGroup(
            p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextArea1)
                    .addGroup(p_principalLayout.createSequentialGroup()
                        .addComponent(b_menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_cerrarVentana)
                        .addGap(87, 87, 87)
                        .addComponent(b_salir)))
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        p_principalLayout.setVerticalGroup(
            p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_menu)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_salir)
                        .addComponent(b_cerrarVentana)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "GRACIAS. HASTA PRONTO.", "GESTIÓN DE EMPRESA ©", -1);
        System.exit(0);
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menuActionPerformed
        VentanaMenu elMenu = new VentanaMenu();
        this.setVisible(false);
        elMenu.setVisible(true);
    }//GEN-LAST:event_b_menuActionPerformed

    private void b_cerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerrarVentanaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cerrarVentanaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //---TABLA TRABAJADOR
        t_trabajador.setModel(moTrab);
        TableRowSorter<ModeloTrabajador> ordenarTrabajadores = new TableRowSorter(moTrab);
        t_trabajador.setRowSorter(ordenarTrabajadores);

        //---TABLA AUTOBUSES
        t_autobus.setModel(moAuto);
        /*TableRowSorter<ModeloAutobuses> ordenarBuses = new TableRowSorter(moAuto);
        t_autobus.setRowSorter(ordenarBuses);*/

        //---TABLA CLIENTES
        ModeloCliente moCli = new ModeloCliente(laGestora.getLosClientes());
        t_cliente.setModel(moCli);
        TableRowSorter<ModeloCliente> ordenarClientes = new TableRowSorter(moCli);
        t_cliente.setRowSorter(ordenarClientes);

        //---TABLA RUTAS
        ModeloRuta moRut = new ModeloRuta(laGestora.getLasRutas());
        t_ruta.setModel(moRut);
        TableRowSorter<ModeloRuta> ordenarRutas = new TableRowSorter(moRut);
        t_ruta.setRowSorter(ordenarRutas);

        //---TABLA FACTURAS
        ModeloFactura moFac = new ModeloFactura(laGestora.getLasFacturas());
        t_factura.setModel(moFac);
        TableRowSorter<ModeloFactura> ordenarFacturas = new TableRowSorter(moFac);
        t_factura.setRowSorter(ordenarFacturas);

    }//GEN-LAST:event_formWindowOpened

    private void b_bajaAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bajaAutobusActionPerformed
        darBajaAutobus();
    }//GEN-LAST:event_b_bajaAutobusActionPerformed

    private void b_bajaTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bajaTrabajadorActionPerformed
        darBajaTrabajador();
    }//GEN-LAST:event_b_bajaTrabajadorActionPerformed

    private void cb_fabricanteCarroceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fabricanteCarroceriaActionPerformed
        fabricante = cb_fabricanteCarroceria.getItemAt(cb_fabricanteCarroceria.getSelectedIndex());
        ModeloAutobuses moAuto = new ModeloAutobuses(laGestora.getLosAutobuses(fabricante));
        t_autobus.setModel(moAuto);
    }//GEN-LAST:event_cb_fabricanteCarroceriaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        p_cambiarClaveUsuario.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void cb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usuarioActionPerformed
        String usuario = cb_usuario.getItemAt(cb_usuario.getSelectedIndex());
        ct_clave.setText(laGestora.getLaClaveUsuario(usuario));
    }//GEN-LAST:event_cb_usuarioActionPerformed

    private void b_cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cambiarClaveActionPerformed
        p_cambiarClaveUsuario.setVisible(b_cambiarClave.isSelected());
    }//GEN-LAST:event_b_cambiarClaveActionPerformed

    private void b_eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarUsuarioActionPerformed
        darBajaUsuario();
    }//GEN-LAST:event_b_eliminarUsuarioActionPerformed

    private void b_limpiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarUsuarioActionPerformed
        limpiar(p_cambiarClaveUsuario);
        limpiar(p_usuarios);
    }//GEN-LAST:event_b_limpiarUsuarioActionPerformed

    private void b_guardarNuevaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarNuevaClaveActionPerformed
        modificarClave();
        b_cambiarClave.setSelected(false);
        limpiar(p_cambiarClaveUsuario);
        limpiar(p_usuarios);
    }//GEN-LAST:event_b_guardarNuevaClaveActionPerformed

    private void darBajaTrabajador() {
        try {
            ArrayList<String> dniSeleccionado = new ArrayList();
            int[] filas = t_trabajador.getSelectedRows();
            for (int i = 0; i < filas.length; i++) {
                Object seleccionado = t_trabajador.getValueAt(filas[i], 0);
                dniSeleccionado.add(seleccionado.toString());
            }
            String[] trabajadorSeleccionado = new String[dniSeleccionado.size()];
            for (int i = 0; i < dniSeleccionado.size(); i++) {
                trabajadorSeleccionado[i] = dniSeleccionado.get(i);
            }
            if (trabajadorSeleccionado.length != 0 && laGestora.borrarTrabajador(trabajadorSeleccionado) == true) {
                if (trabajadorSeleccionado.length == 1) {
                    Mensajes.mensajesDeResultado("TRABAJADOR1");
                    ejecutarAlBorrarDatos();
                } else {
                    Mensajes.mensajesDeResultado("TRABAJADOR2");
                    ejecutarAlBorrarDatos();
                }
                moTrab.setElTrabajador(laGestora.getLosTrabajadores());
                t_trabajador.setModel(moTrab);
            } else {
                Mensajes.mensajesDeError("BAJA_TRABAJADOR");
            }
        } catch (ArrayIndexOutOfBoundsException ex1) {
            Mensajes.mensajesDeError("BAJA_TRABAJADOR");
        } catch (IndexOutOfBoundsException ex2) {
            Mensajes.mensajesDeError("BAJA_TRABAJADOR");
        }
    }

    private void darBajaAutobus() {
        try {
            ArrayList<String> matriculaSeleccionada = new ArrayList();
            int[] fila = t_autobus.getSelectedRows();
            for (int i = 0; i < fila.length; i++) {
                Object seleccionado = t_autobus.getValueAt(fila[i], 0);
                matriculaSeleccionada.add(seleccionado.toString());
            }

            String[] autobusSeleccionado = new String[matriculaSeleccionada.size()];
            for (int i = 0; i < autobusSeleccionado.length; i++) {
                autobusSeleccionado[i] = matriculaSeleccionada.get(i);
            }
            if (autobusSeleccionado.length != 0 && laGestora.borrarAutobus(autobusSeleccionado) == true) {
                if (autobusSeleccionado.length == 1) {
                    Mensajes.mensajesDeResultado("AUTOBUS1");
                    ejecutarAlBorrarDatos();
                } else {
                    Mensajes.mensajesDeResultado("AUTOBUS2");
                    ejecutarAlBorrarDatos();
                }
                moAuto.setElAutobus(laGestora.getLosAutobuses(fabricante));
                t_autobus.setModel(moAuto);
            } else {
                Mensajes.mensajesDeError("BAJA_AUTOBUS");
            }
        } catch (ArrayIndexOutOfBoundsException ex1) {
            Mensajes.mensajesDeError("BAJA_AUTOBUS");

        }
    }
    
    private void darBajaUsuario(){
        String usuario = cb_usuario.getItemAt(cb_usuario.getSelectedIndex());
        if(laGestora.eliminarUsuario(usuario)){
            Mensajes.mensajesDeResultado("BAJA_USUARIO");
            ejecutarAlBorrarDatos();
        }else{
            Mensajes.mensajesDeError("BAJA_USUARIO");
        }
    }
    
    private void modificarClave(){
        String clave1;
        String clave2;
        String claveActual;
        String usuario;
        usuario = cb_usuario.getItemAt(cb_usuario.getSelectedIndex());
        claveActual = ct_clave.getText();
        clave1 = new String(ct_clave1.getPassword());
        clave2 = new String(ct_clave2.getPassword());
        if(clave1.equals(clave2)){
            if(!clave1.equals(claveActual)){
                laGestora.cambiarUsuario(usuario, clave1);
                Mensajes.mensajesDeResultado("CLAVE_CAMBIADA");
            }else{
                Mensajes.mensajesDeError("CLAVES_IGUALES");
            }
        }else{
            Mensajes.mensajesDeError("CLAVES_DISTINTAS");
        }
    }

    private void ejecutarAlBorrarDatos() {
        laGestora.escribirArchivos();
    }
    
    private void limpiar(JPanel elPanel) {
        Component[] losComponentes = elPanel.getComponents();
        for (Component elComponente : losComponentes) {
            if (elComponente instanceof JTextField) {
                JTextField ct = (JTextField) elComponente;
                ct.setText(null);
            }
            if (elComponente instanceof JComboBox) {
                JComboBox cb = (JComboBox) elComponente;
                cb.setSelectedIndex(0);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_bajaAutobus;
    private javax.swing.JButton b_bajaTrabajador;
    private javax.swing.JToggleButton b_cambiarClave;
    private javax.swing.JButton b_cerrarVentana;
    private javax.swing.JButton b_eliminarUsuario;
    private javax.swing.JButton b_guardarNuevaClave;
    private javax.swing.JButton b_limpiarUsuario;
    private javax.swing.JButton b_menu;
    private javax.swing.JButton b_salir;
    private javax.swing.JComboBox<String> cb_fabricanteCarroceria;
    private javax.swing.JComboBox<String> cb_usuario;
    private javax.swing.JTextField ct_clave;
    private javax.swing.JPasswordField ct_clave1;
    private javax.swing.JPasswordField ct_clave2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel p_autobus;
    private javax.swing.JPanel p_cambiarClaveUsuario;
    private javax.swing.JPanel p_cliente;
    private javax.swing.JPanel p_factura;
    private javax.swing.JPanel p_principal;
    private javax.swing.JPanel p_ruta;
    private javax.swing.JPanel p_trabajador;
    private javax.swing.JPanel p_usuarios;
    private javax.swing.JTable t_autobus;
    private javax.swing.JTable t_cliente;
    private javax.swing.JTable t_factura;
    private javax.swing.JTable t_ruta;
    private javax.swing.JTable t_trabajador;
    // End of variables declaration//GEN-END:variables
}
